### ISSUE TITLE
sendData is not working

### ISSUE THREAD

**Issue by medzhidov** [livekit/server-sdk-js#146]
First problem. I am using:

```javascript
await this.client.sendData(roomId, encoder.encode(JSON.stringify(message)), DataPacket_Kind.RELIABLE, {});
```

The data is sent successfully, but none of the recipients receive the data. The client settings are all fine, and I can create and use rooms without any issues.
Second problem: After several minutes of creating a room, this method starts throwing an error 
```
Error: Request failed with status 503: Service Unavailable
    at <anonymous> (./app/backend/node_modules/livekit-server-sdk/dist/TwirpRPC.js:27:14)
    at processTicksAndRejections (:12:39)
      at ./app/backend/src/lib/LiveKitManager.ts:73:13
```
and I don't know why. After creating a new room, the method works for 5-7 minutes before encountering the same error again (but clients do not receive anything in both scenarios).

**Comment by medzhidov** [comment]
I forget to add "room" field while creating access token, so all my participant was in room named "". I think we need an error for this situation
